<p class="tos--paragraph">1. Use of RPG Session-Hub is free, nobody from RPG Session-Hub's owners shall ever contact you requesting money.</p>
<p class="tos--paragraph">2. The only mean of communication with RPG Session-Hub's staff is by using a form in your user panel.</p>
<p class="tos--paragraph">3. RPG Session-Hub may lock your account, delete any content generated by you and forbid you future access to its features. In such case, you shall receive an email specifying the reason.</p>
<p class="tos--paragraph">4. The RPG Session-Hub's Terms Of Service may change whenever needed, but, in case of important changes, users shall be notified prior to it.</p>
<p class="tos--paragraph">5. RPG Session-Hub stores various types of data. This data will never be sold to third party services or even published outside of RPG Session-Hub.</p>
<p class="tos--paragraph">6. All RPG Session-Hub's owners have access to your data, however, they must not access it without proper reasons.</p>
<p class="tos--paragraph">7. Any data collected by RPG Session-Hub may be used in order to improve service's functionality. Users will not be notified of that.</p>
<p class="tos--paragraph">8. You may contact RPG Session-Hub staff and ask for deletion of your data. We shall process your request within 48 hours.</p>
<p class="tos--paragraph">9. Use of RPG Session-Hub is FREE. Report to us any and all attempts of staff attempting to take any money for using the service.</p>
<br />

<div class="tos--button">
    <button role="button" class="btn btn-info tos--button" onclick="window.open('', '_self', ''); window.close();">Close</button>
</div>
